spring:
  application:
    name: api
  datasource:
    url: ${DB_URL:}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false



app:

  jwt:
    secret: ${APP_JWT_SECRET:}
    expiration-minutes: 720
    issuer: kasolution-api


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
